# =========================================
# 狂野飙车 9 (Asphalt 9) 纯净去广告规则
# 更新时间：2026-06
# =========================================

[filter_local]
# > 强制放行 Gameloft 核心鉴权与数据湖 (防断网)
host, gdid.datalake.gameloft.com, direct
host, etsv2.datalake.gameloft.com, direct

# > 第三方 App 广告服务 (底层直接丢弃，最省电)
host, odm.app-ads-services.com, reject

[rewrite_local]
# > 游戏内广告 API 欺骗 (假装请求成功，防无限重试耗电)
^https?:\/\/a314\.gameloft\.com\/ url reject-200
^https?:\/\/201205igp\.gameloft\.com\/ url reject-200
^https?:\/\/l1-1\.anzu\.io\/ url reject-dict
^https?:\/\/logic\.anzuinfra\.com\/ url reject-200
^https?:\/\/events\.prod\.anzu-us\.com\/ url reject-200

[mitm]
# > 对应重写的解密域名
hostname = a314.gameloft.com, 201205igp.gameloft.com, l1-1.anzu.io, logic.anzuinfra.com, events.prod.anzu-us.com