# 亲邻开门去广告规则订阅
# 链接：https://raw.githubusercontent.com/wugejuhao/new-day/main/qlkm_adblock.conf

[rewrite_local]
# 调用你仓库里的 js 脚本来处理数据
^https:\/\/(qadx.*\.qinlinad|mall-dsp.*\.qinlinkeji)\.com url script-response-body https://raw.githubusercontent.com/wugejuhao/new-day/main/qlkm_adblock.js

[mitm]
hostname = qadx*.qinlinad.com, mall-dsp*.qinlinkeji.com
